{{define "handlerPrefix"}}{{with $prefix := .HandlerPrefix}}{{$prefix | printf "%s-"}}{{end -}}{{end}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{template "handlerPrefix" .}}cluster-hosted-keepalived
  namespace: {{ .HandlerNamespace }}
  labels:
    app: cluster-hosted
    component:  cluster-hosted-keepalived
spec:
  selector:
    matchLabels:
      name: {{template "handlerPrefix" .}}cluster-hosted-keepalived
  template:
    metadata:
      labels:
        app: cluster-hosted
        component: cluster-hosted-keepalived
        name: {{template "handlerPrefix" .}}cluster-hosted-keepalived

    spec:
      hostNetwork: true
      serviceAccountName: {{template "handlerPrefix" .}}cluster-hosted-keepalived
      #nodeSelector: {{ toYaml .HandlerNodeSelector | nindent 8 }}
      #tolerations: {{ toYaml .HandlerTolerations | nindent 8 }}
      #affinity: {{ toYaml .HandlerAffinity | nindent 8 }}
      volumes:
      - name: resource-dir
        hostPath:
          path: /etc/kubernetes/static-pod-resources/keepalived
      - name: script-dir
        hostPath:
          path: /etc/kubernetes/static-pod-resources/keepalived/scripts
      - name: kubeconfig
        hostPath:
          path: /etc/kubernetes
      - name: kubeconfigvarlib
        hostPath:
          path: /var/lib/kubelet
      - name: conf-dir
        hostPath:
          path: /etc/keepalived
      - name: run-dir
        empty-dir: {}
      - name: chroot-host
        hostPath:
          path: /
      initContainers:
      - name: cluster-hosted-render-keepalived
        image: https://quay.io/repository/openshift/origin-baremetal-runtimecfg
        command:
        - runtimecfg
        - render
        - /etc/kubernetes/kubeconfig
        - --api-vip
        - {{ onPremPlatformAPIServerInternalIP . }}
        - --ingress-vip
        - {{ onPremPlatformIngressIP . }}
        - /config
        - --out-dir
        - /etc/keepalived
        resources: {}
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubernetes
        - name: script-dir
          mountPath: /config
        - name: conf-dir
          mountPath: /etc/keepalived
        imagePullPolicy: IfNotPresent
      containers:
      - name: cluster-hosted-keepalived
        securityContext:
          privileged: true
        image: https://quay.io/repository/openshift/origin-keepalived-ipfailover
        env:
          - name: NSS_SDB_USE_CACHE
            value: no
        command:
        - /bin/bash
        - -c
        - |
          #/bin/bash
          reload_keepalived()
          {
            if pid=$(pgrep -o keepalived); then
                kill -s SIGHUP "$pid"
            else
                /usr/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --vrrp --log-detail --log-console &
            fi
          }
      
          msg_handler()
          {
            while read -r line; do
              echo "The client sent: $line" >&2
              # currently only 'reload' msg is supported
              if [ "$line" = reload ]; then
                  reload_keepalived
              fi
            done
          }
      
          set -ex
          declare -r keepalived_sock="/var/run/keepalived/keepalived.sock"
          export -f msg_handler
          export -f reload_keepalived
          if [ -s "/etc/keepalived/keepalived.conf" ]; then
              /usr/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --vrrp --log-detail --log-console &
          fi
      
          rm -f "$keepalived_sock"
          socat UNIX-LISTEN:${keepalived_sock},fork system:'bash -c msg_handler'
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: conf-dir
          mountPath: /etc/keepalived
        - name: run-dir
          mountPath: /var/run/keepalived
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              kill -s SIGUSR1 "$(pgrep -o keepalived)" && ! grep -q "State = FAULT" /tmp/keepalived.data
          initialDelaySeconds: 20
        terminationMessagePolicy: FallbackToLogsOnError
        imagePullPolicy: IfNotPresent
      - name: cluster-hosted-keepalived-monitor
        securityContext:
          privileged: true
        image: https://quay.io/repository/openshift/origin-baremetal-runtimecfg
        env:
          - name: ENABLE_UNICAST
            value: yes
          - name: IS_BOOTSTRAP
            value: no
        command:
        - dynkeepalived
        - /var/lib/kubelet/kubeconfig
        - /config/keepalived.conf.tmpl
        - /etc/keepalived/keepalived.conf
        - --api-vip
        - {{ onPremPlatformAPIServerInternalIP . }}
        - --ingress-vip
        - {{ onPremPlatformIngressIP . }}
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: resource-dir
          mountPath: /config
        - name: kubeconfigvarlib
          mountPath: /var/lib/kubelet
        - name: conf-dir
          mountPath: /etc/keepalived
        - name: run-dir
          mountPath: /var/run/keepalived
        - name: chroot-host
          mountPath: /host
        imagePullPolicy: IfNotPresent
      
        
    
