apiVersion: v1
data:
  images.json: |
    {
      "clusterBaremetalOperator": "registry.svc.ci.openshift.org/openshift:cluster-baremetal-operator",
      "baremetalOperator": "registry.svc.ci.openshift.org/openshift:baremetal-operator",
      "baremetalIronic": "registry.svc.ci.openshift.org/openshift:ironic",
      "baremetalIronicInspector": "registry.svc.ci.openshift.org/openshift:ironic-inspector",
      "baremetalIpaDownloader": "registry.svc.ci.openshift.org/openshift:ironic-ipa-downloader",
      "baremetalMachineOsDownloader": "registry.svc.ci.openshift.org/openshift:ironic-machine-os-downloader",
      "baremetalStaticIpManager": "registry.svc.ci.openshift.org/openshift:ironic-static-ip-manager"
    }
kind: ConfigMap
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  name: cluster-hosted-operator-images
  namespace: tst-cluster-hosted-operator
